version: '2'
services:
  nginx:
    build: ./nginx
    ports:
    - "8080:80"
    depends_on:
    - node
  node:
    build: .
    ports:
    - "3000:3000"
    volumes:
    - .:/app
    depends_on:
    - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo
