version: '2'
services:
  nginx:
    build: ./nginx
    ports:
    - "8080:80"
    depends_on:
    - node
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb
    volumes:
      - ./mongo_data:/data/db
  node:
    build: .
    ports:
    - "3000:3000"
    volumes:
    - .:/app
    links:
    - mongodb
