version: '3.2'

services:
  app_blue:
    image: blog_express:v1
    depends_on:
      - nginx-proxy
    working_dir: /app/
    ports:
      - 8888:3000
    environment:
      - VIRTUAL_HOST=nodeapp.local
    volumes:
      - type: bind
        source: ./front
        target: /app/front
      - type: bind
        source: ./server
        target: /app/server
    command: npm start
  
  app_green:
    image: blog_express:v1
    depends_on:
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=nodeapp.local
    volumes:
      - type: bind
        source: ./front
        target: /app/front
      - type: bind
        source: ./server
        target: /app/server 
    command: npm start

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    


