version: '3.2'

services:
  app_blue:
    image: blog_express:v1
    depends_on:
      - nginx-proxy
      - mongo-db
    working_dir: /app/
    networks: 
      - dbconnection
    environment:
      - VIRTUAL_HOST=nodeapp.local
    volumes:
      - type: bind
        source: ./server
        target: /app/server
    command: npm start
  
  app_green:
    image: blog_express:v1
    depends_on:
      - nginx-proxy
      - mongo-db
    working_dir: /app/
    networks: 
      - dbconnection
    environment:
      - VIRTUAL_HOST=nodeapp.local
    volumes:
      - type: bind
        source: ./server
        target: /app/server
    command: npm start

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 8081:80
    networks: 
      - dbconnection
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  
  mongo-db:
    image: mongo
    depends_on:
      - nginx-proxy
    volumes:
      - db-data:/data/db
    networks: 
      - dbconnection
    command: mongod --dbpath "/data/db" 
    
volumes:
  db-data:

networks: 
  dbconnection:
    


