version: "2"
services:
  nginx:
    container_name: nginx_container
    build: ./nginx
    image: spillover427/nginx:blog-latest
    volumes:
      - ./:/app
    depends_on:
      - mongo
    links:
      - web
  web:
    build: .
    container_name: node_container
    image: spillover427/node:blog-latest
    volumes:
      - ./:/app
    ports:
        - "3333:8080"
    links:
      - mongo
    command: npm start
  mongo:
    image: spillover427/mongo:blog-latest
    container_name: mongodb_container
    ports:
      - 27017:27017
    volumes:
       - ./:/data/db
