version: "2"
services:
  nginx:
    container_name: nginx_container
    build: ./nginx
    image: nginx:latest
    volumes:
      - ./:/app
    depends_on:
      - mongo
    links:
      - web
  web:
    build: .
    container_name: node_container
    image: node:latest
    volumes:
      - ./:/app
    ports:
        - "3001:8080"
    links:
      - mongo
    command: npm start
  mongo:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - 27017:27017
    volumes:
      - ./:/data/db
