version: "2"
services:
  nginx:
    container_name: nginx_container
    build: ./nginx
    image: spillover427/nginx:blog-latest
    volumes:
      - ./:/app
    depends_on:
      - mongo
    links:
      - web
    ports:
        - "3333:80"
  web:
    container_name: node_container
    image: spillover427/node:blog-latest
    ports:
        - "3333:3333"
    links:
      - mongo
  mongo:
    image: spillover427/mongo:blog-latest
    container_name: mongodb_container
    ports:
      - 27107:27017
    volumes:
       - ./:/data/db
