version: '2'

services:
  app_blue:
    image: blog_express:v1
    depends_on:
      - nginx-proxy
      - mongo-db
    working_dir: /app/
    ports:
      - 8888:3000
    environment:
      - VIRTUAL_HOST=nodeapp.local
    volumes:
      - ./server:/app/server
    links:
      - mongo-db
    command: npm start
  
  app_green:
    image: blog_express:v1
    depends_on:
      - nginx-proxy
      - mongo-db
    working_dir: /app/
    environment:
      - VIRTUAL_HOST=nodeapp.local
    volumes:
      - ./server:/app/server
    links:
      - mongo-db
    command: npm start

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 8082:80
    links:
      - mongo-db
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  
  mongo-db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./db-data:/data/db
    command: mongod --dbpath "/data/db"
